### ISSUE TITLE
if my image size:256*256,should I modify this model structure

### ISSUE THREAD

**Issue by daixiangzi** [berniwal/swin-transformer-pytorch#18]

**Comment by yangdaowu** [comment]
@daixiangzi Hello, have you solved this problem?

**Comment by daixiangzi** [comment]
Yes.i modify window size



我没有什么天赋，我只是生而由来的执着。


------------------ Original ------------------
From: yangdaowu ***@***.***&gt;
Date: Tue,Dec 21,2021 2:11 PM
To: berniwal/swin-transformer-pytorch ***@***.***&gt;
Cc: daixiangzi ***@***.***&gt;, Mention ***@***.***&gt;
Subject: Re: [berniwal/swin-transformer-pytorch] if my imagesize:256*256,should I modify this model structure (Issue #18)





 
@daixiangzi Hello, have you solved this problem?
 
—
Reply to this email directly, view it on GitHub, or unsubscribe.
Triage notifications on the go with GitHub Mobile for iOS or Android.

**Comment by yangdaowu** [comment]
It's window_ Size? It was originally set to 7. Why did you set it to be better

**Comment by daixiangzi** [comment]
> It's window_ Size? It was originally set to 7. Why did you set it to be better

yes, adapt 256*256 input

**Comment by yangdaowu** [comment]
Ok, thank you for your answer, thank you very much.
