### ISSUE TITLE
Can this be used for target detection? I didn't make it

### ISSUE THREAD

**Issue by kuozhijishou** [berniwal/swin-transformer-pytorch#4]
Can this be used for target detection? I didn't make it

**Comment by berniwal** [comment]
Yes, the authors also used it for object detection by replacing the backbone of the respective object detector with the Swin Transformer. Depending on the object detector I assume you need to either extract the feature map after the last stage (before the global average pooling and linear layer) or for an FPN based approach extract the feature maps from each stage as they do for the ResNet. But in general just changing the backbones and leaving everything else the same should work.

![Selection_376](https://user-images.githubusercontent.com/25658200/113112195-3535a080-9209-11eb-953b-9bc1204f04aa.png)
