### ISSUE TITLE
How to use for generation work

### ISSUE THREAD

**Issue by yinyiyu** [berniwal/swin-transformer-pytorch#5]
Thanks for your great work. I do the task of image generation. In my opinion, the current swin-transformer is an encode structure. Is there a corresponding swin-transformer that can be used for decode?

**Comment by berniwal** [comment]
Thank you for your interest in the code. Unfortunately I am not aware of a corresponding Swin Transformer for the task of image generation. There is some work using Tranformers for autoregressive image generation (https://arxiv.org/pdf/1802.05751.pdf) which might help you to adapt the Swin Transformer in a similar way.

**Comment by yinyiyu** [comment]
Thanks for your advice.
